apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: vmauth-threshold-com
  namespace: vm
spec:
  secretName: vmauth-threshold-com
  issuerRef:
    name: vault-cluster-issuer
    kind: ClusterIssuer
  commonName: vmauth.threshold.com
  dnsNames:
  - vmauth.threshold.com
