apiVersion: operator.victoriametrics.com/v1beta1
kind: VMServiceScrape
metadata:
  name: service-scope-demo
  namespace: roh5server
spec:
  attach_metadata: {}
  endpoints:
  - attach_metadata: {}
    path: /metrics
    port: web
  namespaceSelector:
    matchNames:
    - roh5server
  selector:
    matchExpressions:
    - key: operator.victoriametrics.com/additional-service
      operator: DoesNotExist
    matchLabels:
      app: example-app
