apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
  labels:
    app: registry
  name: registry
  namespace: roh5server
spec:
  replicas: 1
  selector:
    matchLabels:
      app: registry
  template:
    metadata:
      labels:
        app: registry
    spec:
      containers:
      - env:
        - name: REGISTRY_AUTH
          value: htpasswd
        - name: REGISTRY_AUTH_HTPASSWD_REALM
          value: Registry Realm
        - name: REGISTRY_AUTH_HTPASSWD_PATH
          value: /auth/htpasswd
        - name: REGISTRY_HTTP_TLS_CERTIFICATE
          value: /certs/tls.crt
        - name: REGISTRY_HTTP_TLS_KEY
          value: /certs/tls.key
        - name: REGISTRY_STORAGE_FILESYSTEM_ROOTDIRECTORY
          value: /var/lib/registry
        image: registry:2
        imagePullPolicy: IfNotPresent
        name: registry
        ports:
        - containerPort: 5000
          name: registry-port
          protocol: TCP
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        volumeMounts:
        - mountPath: /auth
          name: data
        - mountPath: /certs
          name: secret-volume
          readOnly: true
        - mountPath: /var/lib/registry
          name: txcloud-cbs
      dnsPolicy: ClusterFirst
      initContainers:
      - command:
        - sh
        - -c
        - htpasswd  -Bbn  <user> <password>  >  /auth/htpasswd
        image: httpd:2
        imagePullPolicy: IfNotPresent
        name: auth
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        volumeMounts:
        - mountPath: /auth
          name: data
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
      volumes:
      - emptyDir: {}
        name: data
      - name: secret-volume
        secret:
          defaultMode: 420
          secretName: registry-tls-secret
      - name: txcloud-cbs
        persistentVolumeClaim:
          claimName: local-registry
