apiVersion: v1
kind: LimitRange
metadata:
  name: resource-constraint
  namespace: roh5server
spec:
  limits:
  - default: # 此处定义默认限制值
      cpu: 400m
      memory: 1000Mi
    defaultRequest: ## 此处定义默认请求值
      cpu: 10m
      memory: 50Mi
    max: # max 和 min 定义限制范围
      cpu: "1"
      memory: 1000Mi
    min:
      cpu: 10m
    type: Container
