operator:
  replicas: 1
ipam:
  operator:
    clusterPoolIPv4PodCIDRList: ["10.42.0.0/16"]
kubeProxyReplacement: "true"
k8sServiceHost: "12.0.0.150"
k8sServicePort: "6443"
#启用可观测性
prometheus:
  enabled: true
operator:
  prometheus:
    enabled: true
hubble:
  enabled: true
  metrics:
    enabled:
    - dns
    - drop:sourceContext=pod;destinationContext=pod
    - tcp
    - flow
    - port-distribution
    - httpV2
#启动透明加密
l7Proxy: true
encryption:
  enabled: true
  type: wireguard
