apiVersion: v1
kind: ConfigMap
metadata:
  name: helm-plugin-scripts
  namespace: argocd
data:
  # 类文件键
  generate.sh: |
    #!/bin/sh
    ARGUMENTS=$(echo "$ARGOCD_APP_PARAMETERS" | jq -r '.[] | select(.name == "values-files").array | .[] | "--values=" + .')
    PARAMETERS=$(echo "$ARGOCD_APP_PARAMETERS" | jq -r '.[] | select(.name == "helm-parameters").map | to_entries | map("\(.key)=\(.value)") | .[] | "--set=" + .')
    echo ". $ARGUMENTS $PARAMETERS" | xargs helm template
  get-parameters.sh: |
    #!/bin/sh
    yq e -o=json values.yaml | jq '[{
      name: "helm-parameters",
      title: "Helm Parameters",
      collectionType: "map",
      map: [leaf_paths as $path | {"key": $path | join("."), "value": getpath($path)|tostring}] | from_entries
    }]'
