kind: StorageClass
apiVersion: storage.k8s.io/v1
metadata:
  name: local-storage-consul
provisioner: kubernetes.io/no-provisioner
volumeBindingMode: WaitForFirstConsumer
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: consul-sts-pv-node03
spec:
  capacity:
    storage: 10Gi
  volumeMode: Filesystem
  accessModes:
  - ReadWriteOnce
  persistentVolumeReclaimPolicy: Delete
  storageClassName: local-storage-consul
  local:
    path: /consul/sts/data
  nodeAffinity:
    required:
      nodeSelectorTerms:
      - matchExpressions:
        - key: kubernetes.io/hostname
          operator: In
          values:
          - node03
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: consul-sts-pvc-node03
  namespace: consul
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
  storageClassName: local-storage-consul
