apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: vault-cluster-issuer
spec:
  vault:
    server: https://vault.vault:8200
    path: pki/sign/threshold-dot-com
    caBundle: "LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSURCVENDQWUyZ0F3SUJBZ0lJS2pTNTBaUDd3bll3RFFZSktvWklodmNOQVFFTEJRQXdGVEVUTUJFR0ExVUUKQXhNS2EzVmlaWEp1WlhSbGN6QWVGdzB5TkRBMk1UY3dPREE1TWpOYUZ3MHpOREEyTVRVd09ERTBNak5hTUJVeApFekFSQmdOVkJBTVRDbXQxWW1WeWJtVjBaWE13Z2dFaU1BMEdDU3FHU0liM0RRRUJBUVVBQTRJQkR3QXdnZ0VLCkFvSUJBUURCMmRMUjlmTHVheC9aalRXVEh6L0pMUzNkRmJ3akNVcCt0V00xcTFHK1lRdHdSVHFvZHd3eGdRS1IKZ0ZQNkUvZHpaQ3NJR2ZFTXJpYU41QUF5dFUzNWltNVNPbzZPSnBOMXdwc0ZlUmdvaFNEdzllcjNFc1BaWTRNUAo3eDNSN0grRWIyM1NZRmsvRjQ1dzZuRHNpUHozL3NWOUVUd3pjS0pLcE1vUllUeVAxcENLRzFRcjBCcjRQVTNhCm0wR2pkTWRZVlpVRnpEUlNxVm1EcmZScm12SStBandmWkZIazlDNHR2VGEyMzlzNFJIZ2lTWkhGZkJTOXk2cjkKcXFIRnlVVXdkdVI2MHpOVCs3KzEwWVAraVVEektkVTQ1d1I3cnBnVTJMRk1rNjEzbS9ia2lZQld2eHRNSDZZTQo0OURORS92aG1Bdlgxdmszdlc0NGtyVHdENUZmQWdNQkFBR2pXVEJYTUE0R0ExVWREd0VCL3dRRUF3SUNwREFQCkJnTlZIUk1CQWY4RUJUQURBUUgvTUIwR0ExVWREZ1FXQkJTNVJOazFMTXhBNWx2QXJsbUxQcHBCR2F4Sm9qQVYKQmdOVkhSRUVEakFNZ2dwcmRXSmxjbTVsZEdWek1BMEdDU3FHU0liM0RRRUJDd1VBQTRJQkFRQytvQldxS0VSMwplRUYxT2pYaytlaGcwbkdJOE5MMVVZRU9kUVBPOUU3WFpES1RycjlFTWpNdnd4aGNOZk4zeDQyc1ozaHcrc3ZxCjJOZ1JIZzRUMmZmUlRlN3hNZUluUWpQWm1aaTROb3F3ZHFPUE9vbE1WSGFBTmxYV1QvaVpQa2o3M2s3OHl4SnoKRkp2ZWM5OEtyNnJ0WTdCb084RFNJUEFaUVA4eGc0RzYrRGRET1ZtcnZEQXAzTmlJeGl4T3hIVjZQUzg4UUdHMQoySmUyQnhvZlZ2RE5SUTk3aUU2eUgrZE9iLzB3ektLV0NUekpvekhPTlFibzFjSHJOWnNjcnRFYmhiN29uM25zCm9iVm9icFc1OVkxeWgzVzBQOVowVUJrWU5TRE1JVDhZRXBBNXFFaGdRZkZXeDgzcEptdGlFV09NMjYyZXorQnMKWmJNNGJ5Yld3dVpUCi0tLS0tRU5EIENFUlRJRklDQVRFLS0tLS0K"
    auth:
      kubernetes:
        mountPath: /v1/auth/kubernetes
        role: cluster-issuer
        secretRef:
          name: cluster-issuer-secret
          key: token
