apiVersion: v1
kind: Secret
type: kubernetes.io/basic-auth
metadata:
  name: postgres-secret
  namespace: kc
  labels:
    app: postgres
data:
  db: a2V5Y2xvYWs=
  username: a2V5Y2xvYWs=
  password: V203UTZlUjQ4VGZn
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: postgres-config
  namespace: kc
  labels:
    app: postgres
data:
  postgresql.conf: |
    max_connections = 200
    shared_buffers = 256MB
    effective_cache_size = 768MB
    maintenance_work_mem = 64MB
    checkpoint_completion_target = 0.9
    wal_buffers = 7864kB
    default_statistics_target = 100
    random_page_cost = 1.1
    effective_io_concurrency = 200
    work_mem = 655kB
    huge_pages = off
    min_wal_size = 1GB
    max_wal_size = 4GB
  pg_hba.conf: |
    hostssl all all 10.10.0.0/16 scram-sha-256
    hostssl all all 10.42.0.0/16 scram-sha-256
    hostssl all all 127.0.0.1/32 scram-sha-256
    host all all all reject
