kind: StorageClass
apiVersion: storage.k8s.io/v1
metadata:
  name: dockerfile
provisioner: kubernetes.io/no-provisioner
volumeBindingMode: WaitForFirstConsumer
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: dockerfile-pv
spec:
  capacity:
    storage: 1Gi
  volumeMode: Filesystem
  accessModes:
  - ReadWriteOnce
  persistentVolumeReclaimPolicy: Delete
  storageClassName: dockerfile
  local:
    path: /root/tekton/ci-data/dockerfile
  nodeAffinity:
    required:
      nodeSelectorTerms:
      - matchExpressions:
        - key: kubernetes.io/hostname
          operator: In
          values:
          - debian
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: dockerfile-pvc
  namespace: ci
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  storageClassName: dockerfile
