---
apiVersion: v1
kind: Secret
metadata:
  name: gitlab-secret
  namespace: ci
type: Opaque
stringData:
  secretToken: "12345678"
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  labels:
    app.kubernetes.io/instance: triggers-ingress-resource
  annotations:
    nginx.ingress.kubernetes.io/ssl-redirect: "false"
  name: triggers-ingress-resource
  namespace: ci
spec:
  ingressClassName: traefik
  rules:
  - host: el.hdh5.local.h.xinghuihuyu.cn
    http:
      paths:
      - backend:
          service:
            name: el-roh5server-event-listener
            port:
              number: 8080
        path: /server
        pathType: Prefix
---
apiVersion: triggers.tekton.dev/v1beta1
kind: EventListener
metadata:
  name: roh5server-event-listener
  namespace: ci
spec:
  serviceAccountName: tekton-triggers-example-sa
  triggers:
    - triggerRef: roh5server-listener-trigger
