apiVersion: v1
kind: Secret
metadata:
  name: private-repo-http
  namespace: argocd
  labels:
    argocd.argoproj.io/secret-type: repository
stringData:
  type: git
  url: http://gitlab.x.xinghuihuyu.cn/flux-cd/app-demo.git
  password: basic123
  username: root
