apiVersion: k8s.keycloak.org/v2alpha1
kind: Keycloak
metadata:
  name: kc-1
  namespace: kc
spec:
  instances: 1
  db:
    vendor: postgres
    host: postgres.kc.svc.cluster.local
    port: 5432
    database: keycloak
    schema: keycloak
    usernameSecret:
      name: postgres-secret
      key: username
    passwordSecret:
      name: postgres-secret
      key: password
  http:
    httpEnabled: true
    tlsSecret: kc-tls
  hostname:
    hostname: iam.h.xinghuihuyu.cn
  ingress:
    className: nginx
