apiVersion: triggers.tekton.dev/v1beta1
kind: Trigger
metadata:
  name: roh5server-listener-trigger
  namespace: ci
spec:
  interceptors:
    - name: "verify-gitlab-payload"
      ref:
        name: "gitlab"
        kind: ClusterInterceptor
      params:
        - name: secretRef
          value:
            secretName: "gitlab-secret"
            secretKey: "secretToken"
        - name: eventTypes
          value:
            - "Push Hook"
            - "Tag Push Hook"
    - name: "ro3inter-modify"
      ref:
        name: "ro3inter"
        kind: NamespacedInterceptor
    - name: "CEL filter: only when PRs are opened"
      ref:
        name: "cel"
      params:
        - name: "overlays"
          value:
            - key: branch_tag
              expression: "body.ref.split('/')[2]" #Here we are splitting the body.ref as it gives output "ref/head/<branch name or tag>" with "/" to grep only branch name.
  bindings:
    - ref: roh5server-binding
  template:
    ref: roh5server-trigger-template
---
# Trigger Binding
apiVersion: triggers.tekton.dev/v1beta1
kind: TriggerBinding
metadata:
  name: roh5server-binding
  namespace: ci
spec:
  params:
    - name: image
      value: $(extensions.branch_tag)
---
# Trigger Template
apiVersion: triggers.tekton.dev/v1beta1
kind: TriggerTemplate
metadata:
  name: roh5server-trigger-template
  namespace: ci
spec:
  params:
    - name: image
  resourcetemplates:
    - apiVersion: tekton.dev/v1
      kind: PipelineRun
      metadata:
        generateName: roh5erverpush-image-
      spec:
        pipelineRef:
          name: roh5server-push-image
        #taskRunSpecs:
        #- pipelineTaskName: helm-install-middle
        #  serviceAccountName: tekton-helm-sa
        taskRunTemplate:
          serviceAccountName: tekton-triggers-example-sa
          podTemplate:
            securityContext:
              fsGroup: 65532
        workspaces:
        - name: shared-data
          persistentVolumeClaim:
            claimName: dockerfile-pvc
        #- name: docker-credentials
        #  secret:
        #    secretName: registry-secret
        #    items:
        #      - key: .dockerconfigjson
        #        path: config.json
        #- name: gitlab-credentials
        #  secret:
        #    secretName: git-credentials
        params:
        - name: image
          value: $(tt.params.image)
        #- name: insecure-registry1
        #  value: lb-etkxh0j3-azlwq5ic9dpkotm4.clb.ap-shanghai.tencentclb.com:5000
        - name: insecure-registry2
          value: registry.ro3.xyz
