apiVersion: argoproj.io/v1alpha1
kind: WorkflowTemplate
metadata:
  name: gitlab-clone-kaniko
  namespace: ci
spec:
  serviceAccountName: argo-workflow
  workflowMetadata:
    labels:
      effect: git-clone
  #onExit: clone
  templates:
    - name: clone
      inputs:
        parameters:
          - name: REPO_URL
          - name: REVISION
          - name: GIT_TOKEN_SECRET
          - name: GIT_USERNAME
          - name: TARGET_DIR
      script:
        volumeMounts:
          - mountPath: /workspace/repo
            name: work
        image: bitnami/git
        env:
          - name: TOKEN
            valueFrom:
              secretKeyRef:
                name: '{{inputs.parameters.GIT_TOKEN_SECRET}}'
                key: token
          - name: GIT_USERNAME
            value: '{{ inputs.parameters.GIT_USERNAME }}'
        command: [ bash ]
        source: |
          REPO_URL="{{inputs.parameters.REPO_URL}}"
          REVISION="{{inputs.parameters.REVISION}}"
          DIRPATH="{{ outputs.artifacts.repo.path }}"
          echo "inputs REPO_URL:$REPO_URL REVISION:$REVISION DIRPATH:$DIRPATH"
          rm -rf $DIRPATH
          mkdir -p $DIRPATH && cd $DIRPATH
          PATTERN="http://" && CHANGE="http://$GIT_USERNAME:$TOKEN@" && TOKEN_REPO="${REPO_URL/$PATTERN/"$CHANGE"}"
          git clone $TOKEN_REPO $DIRPATH -b $REVISION
          git rev-parse  --short=8  HEAD  | tr -d '\n'  > short-sha.txt
          git rev-parse --abbrev-ref HEAD | tr -d '\n'  > branch.txt
      outputs:
        artifacts:
        - name: repo
          path: /workspace/repo/{{inputs.parameters.TARGET_DIR}}
          archive:
            tar:
              compressionLevel: 0
        parameters:
        - name: short-sha
          valueFrom:
            path: /workspace/repo/{{inputs.parameters.TARGET_DIR}}/short-sha.txt
        - name: branch
          valueFrom:
            path:  /workspace/repo/{{inputs.parameters.TARGET_DIR}}/branch.txt
    - name: current-ts
      script:
        image: zshusers/zsh:4.3.15
        env:
          - name: TZ
            value: "Asia/Shanghai"
        command: [ zsh ]
        source: |
          date  +"%Y%m%d-%H-%M-%S" | tr -d '\n'
    - name: kaniko
      inputs:
        parameters:
        - name: EXTRA_ARGS
        - name: REPO
        - name: SUBDIR
        - name: IMAGE_NAME
        - name: TAG
      container:
        image: gcr.io/kaniko-project/executor:debug
        imagePullPolicy: IfNotPresent
        args:
          - '{{ inputs.parameters.EXTRA_ARGS }}'
          - --dockerfile=./Dockerfile
          - --context=/workspace/source/./ 
          - --destination={{ inputs.parameters.REPO }}/workflow/{{ inputs.parameters.IMAGE_NAME }}:{{ inputs.parameters.TAG }}
        securityContext:
          runAsUser: 0
        volumeMounts:
        - mountPath: /workspace/source
          name: work
          subPath: '{{ inputs.parameters.SUBDIR }}'
        - mountPath: /kaniko/.docker
          name: kaniko-secret
