---
apiVersion: v1
kind: Service
metadata:
  name: public-api
  namespace: roh5server
  labels:
    app: public-api
spec:
  type: ClusterIP
  ports:
    - port: 8080
      targetPort: 8080
  selector:
    app: public-api
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: public-api
  namespace: roh5server
automountServiceAccountToken: true
---
apiVersion: consul.hashicorp.com/v1alpha1
kind: ServiceDefaults
metadata:
  name: public-api
  namespace: roh5server
spec:
  protocol: "http"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: public-api
  namespace: roh5server
spec:
  replicas: 1
  selector:
    matchLabels:
      service: public-api
      app: public-api
  template:
    metadata:
      labels:
        service: public-api
        app: public-api
      annotations:
        consul.hashicorp.com/connect-inject: "true"
        consul.hashicorp.com/connect-service-upstreams: "product-api:9090, payments:1800"
    spec:
      serviceAccountName: public-api
      containers:
        - name: public-api
          image: hashicorpdemoapp/public-api:v0.0.6
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8080
          env:
            - name: BIND_ADDRESS
              value: ":8080"
            - name: PRODUCT_API_URI
              value: "http://localhost:9090"
            - name: PAYMENT_API_URI
              value: "http://localhost:1800"