#这个配置是给kind使用的，用来表示审计 webhook 配置文件
#它告诉 API Server 在生成审计事件后，应该将这些事件发送到哪里。
apiVersion: v1
kind: Config
clusters:
- name: falco
  cluster:
    server: http://localhost:30007/k8s-audit
#
contexts:
- context:
    cluster: falco-k8saudit
    user: ""
  name: default-context
current-context: default-context
preferences: {}
users: []
