apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: workflow-threshold-com
  namespace: workflow
spec:
  secretName: workflow-threshold-com
  issuerRef:
    name: vault-cluster-issuer
    kind: ClusterIssuer
  commonName: workflow.threshold.com
  dnsNames:
  - workflow.threshold.com
