kind: StorageClass
apiVersion: storage.k8s.io/v1
metadata:
  name: local-storage-workflow
provisioner: kubernetes.io/no-provisioner
volumeBindingMode: WaitForFirstConsumer
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: workflow-pv-node01
spec:
  capacity:
    storage: 1Gi
  volumeMode: Filesystem
  accessModes:
  - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: local-storage-workflow
  local:
    path: /workflow/data
  nodeAffinity:
    required:
      nodeSelectorTerms:
      - matchExpressions:
        - key: kubernetes.io/hostname
          operator: In
          values:
          - node01
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: workflow-space
  namespace: ci
spec:
  storageClassName: local-storage-workflow
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
