apiVersion: apps/v1
kind: Deployment
metadata:
  name: app-1
spec:
  replicas: 2
  selector:
    matchLabels:
      app: app-1
  template:
    metadata:
      labels:
        app: app-1
        monitoring: enabled
    spec:
      containers:
        - name: app-1
          image: thejoud1997/app-1:latest
          ports:
            - containerPort: 3000
              name: http-metrics
          env:
            - name: PORT
              value: "3000"
          resources:
            requests:
              memory: 128Mi
              cpu: 50m
            limits:
              memory: 128Mi
              cpu: 50m
---
apiVersion: v1
kind: Service
metadata:
  name: app-1-service
  labels:
    monitoring: enabled
spec:
  type: NodePort
  ports:
    - port: 80
      targetPort: http-metrics
      name: http-metrics
  selector:
    app: app-1
---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  namespace: default
  name: app-1-monitor
spec:
  selector:
    matchLabels:
      monitoring: enabled
  endpoints:
  - port: http-metrics
  namespaceSelector:
    matchNames:
    - default
