apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: alert-threshold-com
  namespace: monitoring
spec:
  secretName: alert-threshold-com
  issuerRef:
    name: vault-cluster-issuer
    kind: ClusterIssuer
  commonName: alert.threshold.com
  dnsNames:
  - alert.threshold.com
