apiVersion: v1
kind: ConfigMap
metadata:
  name: ro3-micro-cm
  namespace: {{ $.Values.namespace }}
data:
  # 类文件键
  config.yaml: |   
    project_name: {{ $.Values.projectName }}
 
    db1:
      mysql_host: {{ $.Values.mysql }}
      mysql_port: 30016
      mysql_user: root
      mysql_pass: "xxxx"
    
    jwt_key_primary: xxxx
    
    service:
      innersdk:
        # 发货服务地址 (不同sdk方需要由这个类似地址去做适配)
        recharge_url: http://{{ $.Values.host.ro3micro }}/api/recharge/inner              
      simplesdk:
        recharge_url: http://{{ $.Values.host.ro3micro }}/api/recharge/simple
      ro3:
        # 认证与支付接口
        sdk_url: http://{{ $.Values.host.ro3micro }}/jsonrpc                                                
        # innersdk专用参数 (客户端使用提交)
        # 转发服地址
        server_status:
          normal_threshold: 50
          busy_threshold: 90

          # 新服时间范围
          new_time_range: 24h
          # 新服数量范围 (最近开的n个为新服)
          new_range: 10
          # 火爆时间范围
          hot_time_range: 24h
          # 爆满时间范围
          full_time_range: 72h
          # 负载
          load_normal: 50
          load_hot: 90
    recommend:
      recent: 100
    # 服务器api接口地址
    server:
      api_url: http://game-roh5-server-svc-$<SID>.{{ $.Values.namespace }}.svc.cluster.local:10004              #/s$<SID>
      trans_url: wss://{{ $.Values.host.roh5server }}/s$<SID>/$<UID>
    
    redis:
      host: {{ $.Values.redis }}
      port: 30019
      db: 246
      auth: "zxc,./123"
    logger:
      # PanicLevel: 0, FatalLevel: 1, ErrorLevel: 2, WarnLevel: 3, InfoLevel: 4, DebugLevel: 5, TraceLevel: 6
      level: 5
    # 微服务的对外端口号
    port: 18000

    redisconf:
      host: {{ $.Values.redis }}
      port: 30019
      db: 0
      auth: zxc,./123

    nats:
      servers:
      - nats://nats-headless:4222
    consul:
      address: http://consul-server.consul.svc:8500
      #token: fb920fd7-0f8d-92a2-a386-b0bd199c01d4
